config/routes.rb
Doctor::Application.routes.draw do
  
  devise_for   :users
  resources    :admins

  resources    :sub_categories_ds
  resources    :categories_ds
  resources    :patients
  
  resources    :vaidyas, :shallow => true do
    member do
    post :rate
    end
  end
  
  resources    :hospitals, :shallow => true do
    member do
    post :rate
    end
  end
   resources    :contact_docs
  resources    :enquiries
  resources    :users
 
   root  :to => "home#index"
   
      namespace  :user do |user|
          resources    :vaidyas
          resources    :hospitals
          match '/user_registration_path', :to=> 'home#new',   :as => 'root'
      end
  
     
        
     

end

app/models/categories_d.rb
class CategoriesD < ActiveRecord::Base
  has_and_belongs_to_many :vaidyas
  has_and_belongs_to_many :sub_categories_ds
  # Setup accessible (or protected) attributes for your model
  attr_accessible         :name, :sub_categories_d_ids, :categories_d_ids
end

app/controllers/categories_ds_controller.rb
class CategoriesDsController < ApplicationController
  # GET /categories_ds
  # GET /categories_ds.json
  def index
    @categories_ds = CategoriesD.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories_ds }
    end
  end

  # GET /categories_ds/1
  # GET /categories_ds/1.json
  def show
    @categories_d = CategoriesD.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @categories_d }
    end
  end

  # GET /categories_ds/new
  # GET /categories_ds/new.json
  def new
    @categories_d = CategoriesD.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @categories_d }
    end
  end

  # GET /categories_ds/1/edit
  def edit
    @categories_d = CategoriesD.find(params[:id])
  end

  # POST /categories_ds
  # POST /categories_ds.json
  def create
    @categories_d = CategoriesD.new(params[:categories_d])

    respond_to do |format|
      if @categories_d.save
        format.html { redirect_to @categories_d, notice: 'Categories d was successfully created.' }
        format.json { render json: @categories_d, status: :created, location: @categories_d }
      else
        format.html { render action: "new" }
        format.json { render json: @categories_d.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories_ds/1
  # PUT /categories_ds/1.json
  def update
    @categories_d = CategoriesD.find(params[:id])

    respond_to do |format|
      if @categories_d.update_attributes(params[:categories_d])
        format.html { redirect_to @categories_d, notice: 'Categories d was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @categories_d.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories_ds/1
  # DELETE /categories_ds/1.json
  def destroy
    @categories_d = CategoriesD.find(params[:id])
    @categories_d.destroy

    respond_to do |format|
      format.html { redirect_to categories_ds_url }
      format.json { head :ok }
    end
  end
end

app/helpers/categories_ds_helper.rb
module CategoriesDsHelper
end

app/views/categories_ds/_form.html.erb
<%= form_for(@categories_d) do |f| %>
  <% if @categories_d.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categories_d.errors.count, "error") %> prohibited this categories_d from being saved:</h2>

      <ul>
      <% @categories_d.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label      :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories_ds/edit.html.erb
<h1>Editing categories_d</h1>

<%= render 'form' %>

<%= link_to 'Show', @categories_d %> |
<%= link_to 'Back', categories_ds_path %>

app/views/categories_ds/index.html.erb
<h1>Listing categories of Doctors</h1>

<table>
  <tr>
    <th>Name</th>

    <th></th>
  </tr>

<% @categories_ds.each do |categories_d| %>
  <tr>
    <td><%= categories_d.name %></td>

    <td><%= link_to 'Show', categories_d %></td>
    <td><%= link_to 'Edit', edit_categories_d_path(categories_d) %></td>
    <td><%= link_to 'Destroy', categories_d, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<br />
<%= link_to 'New Categories', new_categories_d_path %>

app/views/categories_ds/new.html.erb
<h1>New categories</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_ds_path %>

app/views/categories_ds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @categories_d.name %>
</p>


<%= link_to 'Edit', edit_categories_d_path(@categories_d) %> |
<%= link_to 'Back', categories_ds_path %>