config/routes.rb
Doctor::Application.routes.draw do
  
  devise_for   :users
  resources    :admins

  resources    :sub_categories_ds
  resources    :categories_ds
  resources    :patients
  
  resources    :vaidyas, :shallow => true do
    member do
    post :rate
    end
  end
  
  resources    :hospitals, :shallow => true do
    member do
    post :rate
    end
  end
   resources    :contact_docs
  resources    :enquiries
  resources    :users
 
   root  :to => "home#index"
   
      namespace  :user do |user|
          resources    :vaidyas
          resources    :hospitals
          match '/user_registration_path', :to=> 'home#new',   :as => 'root'
      end
  
     
        
     

end

app/models/sub_categories_d.rb
class SubCategoriesD < ActiveRecord::Base
  has_and_belongs_to_many           :categories_ds
  # Setup accessible (or protected) attributes for your model
  attr_accessible            :name, :categories_d_ids
end

app/controllers/sub_categories_ds_controller.rb
class SubCategoriesDsController < ApplicationController
  # GET /sub_categories_ds
  # GET /sub_categories_ds.json
  def index
    @sub_categories_ds = SubCategoriesD.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sub_categories_ds }
    end
  end

  # GET /sub_categories_ds/1
  # GET /sub_categories_ds/1.json
  def show
    @sub_categories_d = SubCategoriesD.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sub_categories_d }
    end
  end

  # GET /sub_categories_ds/new
  # GET /sub_categories_ds/new.json
  def new
    @sub_categories_d = SubCategoriesD.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sub_categories_d }
    end
  end

  # GET /sub_categories_ds/1/edit
  def edit
    @sub_categories_d = SubCategoriesD.find(params[:id])
  end

  # POST /sub_categories_ds
  # POST /sub_categories_ds.json
  def create
    @sub_categories_d = SubCategoriesD.new(params[:sub_categories_d])

    respond_to do |format|
      if @sub_categories_d.save
        format.html { redirect_to @sub_categories_d, notice: 'Sub categories d was successfully created.' }
        format.json { render json: @sub_categories_d, status: :created, location: @sub_categories_d }
      else
        format.html { render action: "new" }
        format.json { render json: @sub_categories_d.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sub_categories_ds/1
  # PUT /sub_categories_ds/1.json
  def update
    @sub_categories_d = SubCategoriesD.find(params[:id])

    respond_to do |format|
      if @sub_categories_d.update_attributes(params[:sub_categories_d])
        format.html { redirect_to @sub_categories_d, notice: 'Sub categories d was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @sub_categories_d.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_categories_ds/1
  # DELETE /sub_categories_ds/1.json
  def destroy
    @sub_categories_d = SubCategoriesD.find(params[:id])
    @sub_categories_d.destroy

    respond_to do |format|
      format.html { redirect_to sub_categories_ds_url }
      format.json { head :ok }
    end
  end
end

app/helpers/sub_categories_ds_helper.rb
module SubCategoriesDsHelper
end

app/views/sub_categories_ds/_form.html.erb
<%= form_for(@sub_categories_d) do |f| %>
  <% if @sub_categories_d.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sub_categories_d.errors.count, "error") %> prohibited this sub_categories_d from being saved:</h2>

      <ul>
      <% @sub_categories_d.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
   <p><%= f.label       :Select_Category %></p>
    <% for categories_d in CategoriesD.find(:all) %>
         <%= radio_button_tag "sub_categories_d[categories_d_ids][]",categories_d.id, @sub_categories_d.categories_ds.include?(categories_d) %>
              <%= categories_d.name %>
             <% end %></p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sub_categories_ds/edit.html.erb
<h1>Editing sub_categories_d</h1>

<%= render 'form' %>

<%= link_to 'Show', @sub_categories_d %> |
<%= link_to 'Back', sub_categories_ds_path %>

app/views/sub_categories_ds/index.html.erb
<h1>Listing SubCategories of Doctors</h1>

<table>
  <tr>
    <th>Name</th>

    <th></th>
    <th></th>
  </tr>

<% @sub_categories_ds.each do |sub_categories_d| %>
  <tr>
    <td><%= sub_categories_d.name %></td>


    <td><%= link_to 'Show', sub_categories_d %></td>
    <td><%= link_to 'Edit', edit_sub_categories_d_path(sub_categories_d) %></td>
    <td><%= link_to 'Destroy', sub_categories_d, confirm: 'Are you sure?', method: :delete %></td>
  </tr>

 <% end %>
  
</table>

<br />

<%= link_to 'New Sub categories', new_sub_categories_d_path %>

app/views/sub_categories_ds/new.html.erb
<h1>New sub_categories_d</h1>

<%= render 'form' %>

<%= link_to 'Back', sub_categories_ds_path %>

app/views/sub_categories_ds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @sub_categories_d.name %>
</p>


<%= link_to 'Edit', edit_sub_categories_d_path(@sub_categories_d) %> |
<%= link_to 'Back', sub_categories_ds_path %>